### ISSUE TITLE
setName suggestion from the readme is unnecessary

### ISSUE THREAD

**Issue by andrewrk** [Games-by-Mason/shader_compiler#2]
Here's the default selected name:

![image](https://github.com/user-attachments/assets/bec4fcc6-f9f3-46db-b7e3-f1ab7707caa9)

In text form:

```
...
      ├─ run shader_compiler (triangle.vert.spv) cached
...
      └─ run shader_compiler (triangle.frag.spv) cached
...
```

I think in this case it's even better than the suggested one from the readme.

**Comment by MasonRemaley** [comment]
Nice, I thought I checked and didn't get this output--I must have made a mistake, or maybe I was on an older version of zig. Will update!
